name: Bootstrap Terraform Backend

permissions:
  id-token: write

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (dev, test, prod)'
        required: true
        type: choice
        options:
          - dev
          - test
          - main

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run bootstrap script
        run: bash .github/workflows/bootstrap-backend.sh ${{ github.event.inputs.environment }}
