name: PR Terraform Backend Setup

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - main    # only run on PRs targeting main
    types: [opened, reopened, synchronize]

jobs:
  setup-pr-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run PR backend bootstrap
        run: bash .github/workflows/bootstrap-pr.sh ${{ github.event.pull_request.number }}
