name: Cleanup PR Terraform Backend

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - main    # only run on PRs targeting main
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      environment: pr${{ github.event.pull_request.number }}
      RESOURCE_GROUP: prenv-management-RG
      STORAGE_ACCOUNT: tfstateprenvfozzen
      LOCATION: westeurope
      PR_ID: ${{ github.event.pull_request.number }}
      BACKEND_CONTAINER: tfstate-pr${{ github.event.pull_request.number }}
    defaults:
      run:
        working-directory: .github/Terraform
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=$RESOURCE_GROUP" -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=tfstate-$environment" -backend-config="key=terraform.tfstate" -backend-config="use_oidc=true"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false -var location=$location -var environment=$environment

      - name: Delete PR container
        run: |
          echo "Deleting container: $BACKEND_CONTAINER"
          az storage container delete \
            --name "$BACKEND_CONTAINER" \
            --account-name "$STORAGE_ACCOUNT" \
            --auth-mode login