name: Cleanup PR Terraform Backend

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - main    # only run on PRs targeting main
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Delete PR container
        run: |
          PR_ID=${{ github.event.pull_request.number }}
          CONTAINER_NAME="tfstate-pr${PR_ID}"

          echo "Deleting container: $CONTAINER_NAME"
          az storage container delete \
            --name "$CONTAINER_NAME" \
            --account-name tfstateprenvfozzen \
            --yes
