name: 'Terraform Deployment'

on:
  push:
    branches:
      - dev
      - test
      - main
  pull_request:
    branches:
      - main    # only PRs to main
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - dev
          - test
          - main

permissions:
  id-token: write
  contents: read

env:
  location: westeurope
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  RESOURCE_GROUP: prenv-management-RG
  STORAGE_ACCOUNT: tfstateprenvfozzen

jobs:
  setup-pr-backend:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      container_name: ${{ steps.bootstrap.outputs.container_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run PR backend bootstrap
        id: bootstrap
        run: bash .github/workflows/bootstrap-pr.sh ${{ github.event.pull_request.number }}

  terraform:
    needs: [setup-pr-backend]
    name: Deploy Terraform
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    defaults:
      run:
        working-directory: .github/Terraform
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Determine environment & backend container
        id: env
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            ENVIRONMENT="pr${{ github.event.pull_request.number }}"
            CONTAINER_NAME="${{ needs.setup-pr-backend.outputs.container_name }}"
          else
            ENVIRONMENT="${{ github.event.inputs.environment || 'dev' }}"
            CONTAINER_NAME="tfstate-$(echo "$ENVIRONMENT" | tr '[:upper:]' '[:lower:]')"
          fi

          echo "Environment: $ENVIRONMENT"
          echo "Container: $CONTAINER_NAME"

          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "container_name=$CONTAINER_NAME" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=$RESOURCE_GROUP" \
            -backend-config="storage_account_name=$STORAGE_ACCOUNT" \
            -backend-config="container_name=${{ steps.env.outputs.container_name }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="use_oidc=true"

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false \
              -var "environment=${{ steps.env.outputs.environment }}" \
              -var "location=$location"

      - name: Terraform Apply
        if: github.event_name != 'pull_request'
        run: terraform apply -auto-approve -input=false \
              -var "environment=${{ steps.env.outputs.environment }}" \
              -var "location=$location"
